// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { FIFO } from "./FIFO.js";
import { get } from "./get.js";
import { getAll } from "./getAll.js";
import { getAllOr } from "./getAllOr.js";
import { getAllOrElse } from "./getAllOrElse.js";
import { getAllOrThrow } from "./getAllOrThrow.js";
import { getOr } from "./getOr.js";
import { getOrElse } from "./getOrElse.js";
import { getOrThrow } from "./getOrThrow.js";
import { has } from "./has.js";
import { hasAll } from "./hasAll.js";
import { hasAny } from "./hasAny.js";
import { hasNone } from "./hasNone.js";
import { LFU } from "./LFU.js";
import { LRU } from "./LRU.js";
import { LRUTTL } from "./LRUTTL.js";
import { Map } from "./Map.js";
import { remove } from "./remove.js";
import { removeAll } from "./removeAll.js";
import { set } from "./set.js";
import { setAll } from "./setAll.js";
import { WeakMap } from "./WeakMap.js";

export const Cache = {
    FIFO,
    get,
    getAll,
    getAllOr,
    getAllOrElse,
    getAllOrThrow,
    getOr,
    getOrElse,
    getOrThrow,
    has,
    hasAll,
    hasAny,
    hasNone,
    LFU,
    LRU,
    LRUTTL,
    Map,
    remove,
    removeAll,
    set,
    setAll,
    WeakMap,
}
