// Generated by @monstermann/barrels
/* eslint-disable */
/* prettier-ignore */
// dprint-ignore-file
// biome-ignore lint: disable

import { FIFO } from "./FIFO.js";
import { FIFOCache } from "./FIFO.js";
import { get } from "./get.js";
import { getAll } from "./getAll.js";
import { getAllOr } from "./getAllOr.js";
import { getAllOrElse } from "./getAllOrElse.js";
import { getAllOrThrow } from "./getAllOrThrow.js";
import { getOr } from "./getOr.js";
import { getOrElse } from "./getOrElse.js";
import { getOrThrow } from "./getOrThrow.js";
import { has } from "./has.js";
import { hasAll } from "./hasAll.js";
import { hasAny } from "./hasAny.js";
import { hasNone } from "./hasNone.js";
import { LFU } from "./LFU.js";
import { LFUCache } from "./LFU.js";
import { LFUCacheEntry } from "./LFU.js";
import { LRU } from "./LRU.js";
import { LRUCache } from "./LRU.js";
import { LRUTTL } from "./LRUTTL.js";
import { LRUTTLCache } from "./LRUTTL.js";
import { Map } from "./Map.js";
import { MapCache } from "./Map.js";
import { remove } from "./remove.js";
import { removeAll } from "./removeAll.js";
import { set } from "./set.js";
import { setAll } from "./setAll.js";
import { WeakMap } from "./WeakMap.js";
import { WeakMapCache } from "./WeakMap.js";

interface Cache<K, V> {
    del: (key: K) => void
    get: (key: K) => V | undefined
    has: (key: K) => boolean
    set: (key: K, value: V) => void
}

declare namespace Cache {
    export {
        FIFO,
        get,
        getAll,
        getAllOr,
        getAllOrElse,
        getAllOrThrow,
        getOr,
        getOrElse,
        getOrThrow,
        has,
        hasAll,
        hasAny,
        hasNone,
        LFU,
        LRU,
        LRUTTL,
        Map,
        remove,
        removeAll,
        set,
        setAll,
        WeakMap,
    }
}

export {
    Cache,
    FIFOCache,
    LFUCache,
    LFUCacheEntry,
    LRUCache,
    LRUTTLCache,
    MapCache,
    WeakMapCache,
}
